# Generated by Django 5.1.4 on 2025-01-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('northeast_latitude', models.FloatField()),
                ('northeast_longitude', models.FloatField()),
                ('southwest_latitude', models.FloatField()),
                ('southwest_longitude', models.FloatField()),
            ],
            options={
                'db_table': 'cities',
                'db_table_comment': 'Table containing coordinate information of cities of Türkiye',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('northeast_latitude', models.FloatField()),
                ('northeast_longitude', models.FloatField()),
                ('southwest_latitude', models.FloatField()),
                ('southwest_longitude', models.FloatField()),
                ('city', models.ForeignKey(db_column='city_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='places.city')),
            ],
            options={
                'db_table': 'districts',
                'db_table_comment': 'Table containing coordinate information of districts of Türkiye',
            },
        ),
    ]
