# Generated by Django 5.1.4 on 2025-02-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityVegetation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('family_link', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('gbif_number', models.IntegerField()),
                ('gbif_link', models.TextField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(db_column='city_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='places.city')),
            ],
            options={
                'db_table': 'city_vegetations',
                'db_table_comment': 'Table containing vegetation information of cities of Türkiye',
            },
        ),
        migrations.CreateModel(
            name='DistrictVegetation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('family_link', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('gbif_number', models.IntegerField()),
                ('gbif_link', models.TextField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(db_column='district_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='places.district')),
            ],
            options={
                'db_table': 'district_vegetations',
                'db_table_comment': 'Table containing vegetation information of districts of Türkiye',
            },
        ),
    ]
