# Generated by Django 5.1.4 on 2025-02-12 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0005_rename_description_allergen_images_allergen_family_and_more'),
        ('places', '0002_cityvegetation_districtvegetation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityvegetation',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='cityvegetation',
            name='family_link',
        ),
        migrations.RemoveField(
            model_name='cityvegetation',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='cityvegetation',
            name='gbif_link',
        ),
        migrations.RemoveField(
            model_name='cityvegetation',
            name='images',
        ),
        migrations.RemoveField(
            model_name='cityvegetation',
            name='species_name',
        ),
        migrations.RemoveField(
            model_name='districtvegetation',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='districtvegetation',
            name='family_link',
        ),
        migrations.RemoveField(
            model_name='districtvegetation',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='districtvegetation',
            name='gbif_link',
        ),
        migrations.RemoveField(
            model_name='districtvegetation',
            name='images',
        ),
        migrations.RemoveField(
            model_name='districtvegetation',
            name='species_name',
        ),
        migrations.AddField(
            model_name='cityvegetation',
            name='allergen',
            field=models.ForeignKey(db_column='allergen_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='allergies.allergen'),
        ),
        migrations.AddField(
            model_name='districtvegetation',
            name='allergen',
            field=models.ForeignKey(db_column='allergen_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='allergies.allergen'),
        ),
    ]
