# Generated by Django 5.1.4 on 2025-02-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0005_rename_description_allergen_images_allergen_family_and_more'),
        ('places', '0003_remove_cityvegetation_common_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityvegetation',
            name='allergen',
            field=models.ForeignKey(db_column='allergen_id', default=2, on_delete=django.db.models.deletion.PROTECT, to='allergies.allergen'),
        ),
        migrations.AlterField(
            model_name='districtvegetation',
            name='allergen',
            field=models.ForeignKey(db_column='allergen_id', default=2, on_delete=django.db.models.deletion.PROTECT, to='allergies.allergen'),
        ),
    ]
