# Generated by Django 5.1.4 on 2025-02-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0006_alter_allergen_allergen_type'),
        ('places', '0004_alter_cityvegetation_allergen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityvegetation',
            name='allergen',
            field=models.ForeignKey(db_column='allergen_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='allergies.allergen'),
        ),
        migrations.AlterField(
            model_name='districtvegetation',
            name='allergen',
            field=models.ForeignKey(db_column='allergen_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='allergies.allergen'),
        ),
    ]
