# Generated by Django 5.1.4 on 2025-05-01 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0006_alter_allergen_allergen_type'),
        ('places', '0005_alter_cityvegetation_allergen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='allergies.commonregion'),
        ),
    ]
