# Generated by Django 5.1.4 on 2025-05-01 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0006_alter_allergen_allergen_type'),
        ('places', '0006_city_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.PROTECT, to='allergies.commonregion'),
        ),
    ]
