# Generated by Django 5.1.4 on 2025-01-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('users', '0002_alter_allergicuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergicuser',
            name='residence_district',
            field=models.ForeignKey(db_column='residence_district_id', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.district'),
        ),
    ]
