# Generated by Django 5.1.4 on 2025-01-01 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('users', '0003_alter_allergicuser_residence_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergicuser',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='allergicuser',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='allergicuser',
            name='residence_district',
            field=models.ForeignKey(db_column='residence_district_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='places.district'),
        ),
    ]
