# Generated by Django 5.1.4 on 2025-01-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_allergicuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergicuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
