# Generated by Django 5.1.4 on 2025-01-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_allergicuser_photo_alter_travel_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='path',
        ),
    ]
