# Generated by Django 5.1.4 on 2025-01-31 12:23

import common.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_travel_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergicuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=common.utilities.define_user_photo_path),
        ),
    ]
