# Generated by Django 5.1.4 on 2025-03-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_allergicuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergicuser',
            name='photo',
        ),
    ]
