# Generated by Django 5.1.4 on 2025-03-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_allergicuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergicuser',
            name='is_male',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
