# Generated by Django 5.1.4 on 2025-01-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAllergyAttackPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ai_prediction', models.FloatField()),
                ('had_allergy_attack', models.BooleanField()),
                ('district', models.ForeignKey(db_column='district_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='places.district')),
            ],
            options={
                'db_table': 'ai_allergy_attack_predictions',
                'db_table_comment': 'Table that contains predictions and actual results for each district at the travel for AllerGeo',
            },
        ),
    ]
