# Generated by Django 5.1.4 on 2025-01-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='models/')),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'models',
                'db_table_comment': 'Table that contains AI model information for AllerGeo',
            },
        ),
        migrations.AlterField(
            model_name='aiallergyattackprediction',
            name='ai_prediction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiallergyattackprediction',
            name='had_allergy_attack',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiallergyattackprediction',
            name='model',
            field=models.ForeignKey(db_column='model_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='predictors.aimodel'),
        ),
    ]
