# Generated by Django 5.1.4 on 2025-01-03 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0003_aimodel_and_more'),
        ('users', '0006_remove_travel_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiallergyattackprediction',
            name='travel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.travel'),
        ),
    ]
