# Generated by Django 5.1.4 on 2025-01-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0004_aiallergyattackprediction_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
