# Generated by Django 5.1.4 on 2025-01-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0005_aimodel_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='update_date',
            new_name='last_update_date',
        ),
    ]
