# Generated by Django 5.1.4 on 2025-02-13 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0007_alter_aiallergyattackprediction_ai_prediction_and_more'),
        ('users', '0007_alter_allergicuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiallergyattackprediction',
            name='travel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.travel'),
        ),
    ]
