# Generated by Django 5.1.4 on 2025-04-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0008_alter_aiallergyattackprediction_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiallergyattackprediction',
            name='selected_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiallergyattackprediction',
            name='selected_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
