# Generated by Django 5.1.4 on 2025-01-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=255)),
                ('description', models.CharField(verbose_name=255)),
            ],
            options={
                'db_table': 'allergens',
                'db_table_comment': 'A table that contains common allergies for AllerGeo',
            },
        ),
        migrations.CreateModel(
            name='AllergenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=255)),
            ],
            options={
                'db_table': 'allergen_types',
                'db_table_comment': 'Table that contains allergen categories for AllerGeo',
            },
        ),
        migrations.CreateModel(
            name='CommonRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=255)),
                ('description', models.CharField(verbose_name=255)),
            ],
            options={
                'db_table': 'common_regions',
                'db_table_comment': 'Table that contains regions of Türkiye for AllerGeo',
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('importance_level', models.IntegerField()),
            ],
            options={
                'db_table': 'user_allergies',
                'db_table_comment': 'Table that contains allergy data of users for AllerGeo',
            },
        ),
        migrations.CreateModel(
            name='AllergenRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(db_column='allergen_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='allergies.allergen')),
            ],
            options={
                'db_table': 'allergen_regions',
                'db_table_comment': 'Table that contains allergen regions for AllerGeo',
            },
        ),
        migrations.AddField(
            model_name='allergen',
            name='allergen_type',
            field=models.ForeignKey(db_column='allergen_type_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='allergies.allergentype'),
        ),
        migrations.CreateModel(
            name='AllergyAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('notes', models.CharField(verbose_name=255)),
                ('allergen', models.ForeignKey(db_column='allergen_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='allergies.allergen')),
                ('district', models.ForeignKey(db_column='district_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='places.district')),
            ],
            options={
                'db_table': 'allergy_attacks',
                'db_table_comment': 'Table that contains allergy attack information of users for AllerGeo',
            },
        ),
    ]
