# Generated by Django 5.1.4 on 2025-01-01 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allergies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allergyattack',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allergenregion',
            name='common_region',
            field=models.ForeignKey(db_column='common_region_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='allergies.commonregion'),
        ),
        migrations.AddField(
            model_name='userallergy',
            name='allergen',
            field=models.ForeignKey(db_column='allergen_id', default=None, on_delete=django.db.models.deletion.PROTECT, to='allergies.allergen'),
        ),
        migrations.AddField(
            model_name='userallergy',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
