# Generated by Django 5.1.4 on 2025-01-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='allergentype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='allergyattack',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonregion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonregion',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
