# Generated by Django 5.1.4 on 2025-01-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0003_alter_allergen_description_alter_allergen_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userallergy',
            name='importance_level',
            field=models.IntegerField(default=1),
        ),
    ]
