# Generated by Django 5.1.4 on 2025-02-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0004_alter_userallergy_importance_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergen',
            old_name='description',
            new_name='images',
        ),
        migrations.AddField(
            model_name='allergen',
            name='family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allergen',
            name='family_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allergen',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allergen',
            name='species_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AllergyAttack',
        ),
    ]
