# Generated by Django 5.1.4 on 2025-02-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0005_rename_description_allergen_images_allergen_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='allergen_type',
            field=models.ForeignKey(db_column='allergen_type_id', default=2, on_delete=django.db.models.deletion.PROTECT, to='allergies.allergentype'),
        ),
    ]
